version: 2

models:
  - name: trans_sales_orders
    columns:
      - name: SalesOrderID
        tests:
          - unique
          - not_null
      - name: CustomerID
        tests:
          - not_null
